apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: device-platform
spec:
  #storageClassName: choose a className in the existing list or keep the default from the cluster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi