# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: StatisticAPI Build and Test

on:
    push:
      branches:    
        - '**' 
        - '!main'          
    pull_request: 
      branches:
        - 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: StatisticAPI - Install dependencies
      run: |
        cd ./statistics-api
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
    - name: Lint code
      continue-on-error: true
      run: |
        cd ./statistics-api
        pip install ruff
        ruff check .
    - name: StatisticAPI - Run tests
      continue-on-error: true
      run: |
        echo "Running tests"
        cd ./statistics-api
        pip install pytest
        python -m pytest tests/ -v

   
  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get StatisticAPI version
        id: version
        run: |
          cd ./statistics-api
          VERSION=$(python3 -c "from app.__version__ import __version__; print(__version__)")
          echo "statistics-api-version=$VERSION" >> $GITHUB_OUTPUT
          echo "image-tag=${VERSION}-$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Increment patch version
        id: increment_version
        run: |
          VERSION=${{ steps.get_version.outputs.statistics-api-version }}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          # Increment patch
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "image-tag=${NEW_VERSION}-$(date +%Y%m%d)" >> $GITHUB_OUTPUT      
          echo "__version__ = '$NEW_VERSION'" > ./statistics-api/app/__version__.py
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./statistics-api
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/statistics-api:${{ steps.version.outputs.image-tag }}

      - name: Commit new version
        run: |
          git add ./statistics-api/app/__version__.py
          git commit -m "ci: bump version to ${{ steps.increment_version.outputs.new-version }}"
          git push origin main

  
